#!/bin/bash -ex

cat > "${OPENHAB_USERDATA}/etc/keys.properties" <<EOF
#
# For security reason, the default auto-signed key is disabled.
#

openhab=AAAAB3Nz...,_g_:admingroup
_g_\:admingroup = group,admin,manager,viewer

EOF
