name: Build and Push OpenHAB image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: setup_build
        uses: docker/setup-buildx-action@v1

      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV

      - name: Get the Git commit reference
        id: vcs_reference
        run: |
          echo "{vcs_ref}={$(git rev-parse HEAD)}" >> $GITHUB_ENV

      - name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          build-args: |
            BUILD_DATE=${{ env.date }}
            JAVA_VERSION=17
            VCS_REF=${{ env.vsc_ref }}
            OPENHAB_VERSION=4.1.1
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/openhab:latest , ${{ secrets.DOCKER_HUB_USERNAME }}/openhab:4.1.1

      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
